name: Enviar Mensaje Diario

on:
  schedule:
    # 22:00 UTC son las 18:00 en Chile (UTC-4)
    - cron: '0 22 * * *'
  workflow_dispatch: # Esto te permite ejecutarlo manualmente cuando quieras

jobs:
  enviar_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests deep-translator

      - name: Ejecutar script de mensajes
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python mensajes.py
