name: Enviar Mensaje Diario

on:
  # Se comenta el schedule para que el bot no se active automaticamente
  # schedule:
  #   - cron: '0 22 * * *'
  
  # Se mantiene activo el dispatch para poder probarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  enviar_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests deep-translator

      - name: Ejecutar script de mensajes
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python mensajes.py
